# Generated by Django 2.2.10 on 2021-11-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
