# Generated by Django 2.2.10 on 2021-11-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_form_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='completed',
            new_name='submitted',
        ),
        migrations.AddField(
            model_name='form',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
