# Generated by Django 2.2.10 on 2021-11-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20211104_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='respondent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form', to='surveys.Respondent'),
        ),
    ]
