# Generated by Django 2.2.10 on 2021-11-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20211104_1546'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.UniqueConstraint(fields=('form', 'question'), name='unique_answer_to_question_in_form'),
        ),
    ]
